### ISSUE TITLE
GetLowestOfferListingsForASIN does not accept ItemCondition

### ISSUE THREAD

**Issue by goshkoy** [ericblade/mws-advanced#121]
According to docs of mws ItemCondition is acceptable parameter GetLowestOfferListingsForASIN, but in the library validation does not accept this parameter, anyway to work around this, cause we're going in production tommorow and i really need it?

**Comment by goshkoy** [comment]
Found a way to workaround it using, doRequest
const response = await mws.doRequest({ 
                path: '/Products/2011-10-01',
                query:{ 
                    MarketplaceId: marketPlaceId,
                    'ASINList.ASIN.1': item.item_id,
                    ItemCondition: 'New',
                    Action: 'GetLowestOfferListingsForASIN',
                    Version: '2011-10-01' 
                },
            feedContent: undefined 
});

Feel free to add it to next releases @ericblade

**Comment by ericblade** [comment]
Pretty exciting to hear something's going "in production" using this :) Let me know what it is, if you can? thanks!

Thanks for letting me know about this.  I do see that in the docs, also for GetLowestOfferListingsForSKU .. I'll add those to the validation.  I'm not sure if I just missed those when I put the validation in, or if it might be something amazon has added in place since then, but it's an easy enough change.

**Comment by ericblade** [comment]
fixed in 2.0.3

**Comment by goshkoy** [comment]
Thank you will update next release cycle

**Comment by ericblade** [comment]
no problem.  if i may ask, are you doing something that is end-user oriented, or something internal?

**Comment by goshkoy** [comment]
End user oriented
