### ISSUE TITLE
Error with this binding

### ISSUE THREAD

**Issue by pwrnrd** [ericblade/mws-advanced#77]
I'm trying to do the following:

````
export default async function () {
    mws.init({
        accessKeyId: '',
        secretAccessKey: '',
        merchantId: ''
    });
    const startDate = new Date('2018-05-24');
    const query = {       
        CreatedAfter: startDate,
        MarketplaceId: ["ATVPDKIKX0DER"],
    }
    let orders = await mws.listOrders(query);
    return orders;
}
````
This code throws the following error: `TypeError: Cannot read property 'mws' of undefined` . 

The error is related to the following function.

`````
function requestPromise(requestData, opt = {}) {
    return new Promise((function reqPromise(resolve, reject) { // eslint-disable-line prefer-arrow-callback
        const mwsInterface = this.mws || mws;
        mwsInterface.request(requestData, (err, result) => {
            if (err) {
                reject(err);
            } else {
                resolve(opt.noFlatten ? result : flattenResult(result));
            }
        });
    }).bind(this));
}
`````
By running my code, the "this"-object is undefined.

I'm not sure whether this is a bug or whether I'm doing something wrong...

**Comment by ericblade** [comment]
Hmm. Didn't think that "this" could end up undefined going in there, which would certainly cause that.  It's a bit of an artifact of trying to make it so you could use new to get new instances, instead of just using the default instance.

If you change the line in requestPromise

```` const mwsInterface = this.mws || mws;````

to

````const mwsInterface = this && this.mws ? this.mws : mws;````

it looks like it should fix that.  I'm away from PC for a bit, so if you get a chance to try that, let me know?

**Comment by pwrnrd** [comment]
This fixed it! Thank you!

Wouldn't it be bettter to get rid of the this binding? Perhaps pass the object that you want to initiate as an argument to the function? Personnaly I don't feel comfortable to rely on the global object.

**Comment by ericblade** [comment]
should be fixed if you pull the latest with ```npm install --save mws-advanced```` .. apologies for the update that broke you :)  if you're using listOrderItems, make sure to update the keys you're using to access the output results to expect camelCase . . sorry, updating some of the older items to be consistent with the newer functions. :)

**Comment by pwrnrd** [comment]
The breaking change cost me a lot of time to figure out yesterday, but that was mostly because it was not documented. I saw that you documented the camelCase update as a breaking change so I figured that this had to be an error on my side... So figuring out that it was not on my side took the most time. But anyways, you don't need to apologies, I love what you do with the project and I know you do the best you can. So thank you for that!!

I'm just trying to help out by reporting the issues that I encounter.

Related to this issue, don't you want to get rid of the "this" object entirely and just pass the class of which you want to create an instance as an argument? Or will that break the code?

**Comment by ericblade** [comment]
It wasn't supposed to break anything, I thought I had good tests for both using mws.init() directly and using new mws.MWSAdvanced(), and that adding new MWSAdvanced() did not break calling init() directly.  I didn't consider that 'this' could be undefined, should probably add a test for that type of use, since if 'this' being weird propagates into unexpected places, it could cause problems.

Not sure exactly what you're suggesting there.  In requestPromise, it is trying to decide if 'this' is an instance of MWSAdvanced() and use the mws-simple that belongs to it.... or, if not, then use the mws-simple that belongs to the module callEndpoint.   It'd probably be better if the class had a different function than the lib for it, but i'd have to dig into it to see if that's something that's not worth the effort.

Overall, I probably should've built it as a prototype class to begin with, but i hadn't considered the case of using it for multiple simultaneous users.
